spring.config.import=classpath:application.yaml
spring.application.name=kpaas
spring.profiles.active=prod

server.port=11000

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://mariadb.cytc26sga3jx.us-east-1.rds.amazonaws.com:3306/myDB
spring.datasource.username=poly
spring.datasource.password=1234
mybatis.type-aliases-package=kopo.poly.kpaas.dto
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=edwerd0511@naver.com
spring.mail.password=ZWK2PF2PKKRK
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

coolsms.api.key=NCSCRQZSCLASB9GF
coolsms.api.secret=PO6P52XXRTLSZS3HMDTLFES4ZIM0A9Z2
coolsms.sender=01072350602
