spring.config.import=classpath:application.yaml
spring.application.name=kpaas
spring.profiles.active=prod

server.port=11000

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${secure.datasource.url}
spring.datasource.username=${secure.datasource.username}
spring.datasource.password=${secure.datasource.password}
mybatis.type-aliases-package=kopo.poly.kpaas.dto
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

openai.api.key=${secure.openai.api-key}

spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=${secure.mail.username}
spring.mail.password=${secure.mail.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

openai.api.key=${secure.openai.api-key}

coolsms.api.key=${secure.coolsms.api.key}
coolsms.api.secret=${secure.coolsms.api.secret}
coolsms.sender=${secure.coolsms.api.sender}


# google cloud vision api key
google.credentials.path=keys/kpaas-vision-key.json

# max file size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# hikari warning
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=300000
